# <center>Regression Problem</center>
## Import Panda and Numpy Library

In [1]:
# Import the libraries
import numpy as np
import pandas as pd

## Load The DataSet From The Local Directory

In [2]:
# Import the Dataset using pandas
Train = pd.read_csv(r'Train_data_regression.csv') # path
Test = pd.read_csv(r'Test_data_regression.csv') # path

## Load The DataSet From The Local Directory

In [3]:
# Display first 10 rows in Train dataset
display(Train.head(10))

,0,1,2,3,4,5,6,7,8,9,...,141,142,143,144,145,146,147,148,149,y
0,-0.746945,0.846646,-0.202470,0.028677,-0.229053,0.378089,-0.800458,0.414641,-1.504229,0.371135,...,-0.990873,0.864308,0.042010,-0.196266,-0.698771,-0.994566,-0.500914,0.003735,-0.353331,-456.665254
1,0.267893,0.686836,-2.099945,-0.356856,0.299254,0.098733,1.206721,-1.172500,-0.227677,2.061577,...,-0.540844,1.059226,-0.691391,0.029994,-0.566103,-0.885774,-1.312298,-0.938679,-1.134801,1058.205923
2,0.774361,0.812023,1.057683,-1.461385,-0.924284,0.323890,1.866386,0.326994,1.286274,-0.996723,...,0.247075,1.203377,0.765125,-0.427309,-0.563282,0.282035,0.126215,0.572231,-1.147129,-434.143673
3,-0.625636,-0.827090,0.602128,1.168934,0.814647,-0.800436,0.218008,0.355778,-0.448102,1.697075,...,0.717384,0.653825,1.290715,-0.439905,-0.202368,0.490357,-0.201219,-1.294190,-0.316879,977.514618
4,-0.976274,-0.673587,-0.103793,-0.076868,0.751871,0.097609,1.686413,-0.369834,1.308027,-0.979400,...,0.653964,0.200234,-0.079921,-1.305642,-0.837960,0.324081,1.216420,-0.520947,0.618585,-15.042199
5,-0.854954,-0.768267,1.171814,-0.695971,1.264707,1.295418,-0.984890,0.762152,-0.003448,1.356186,...,-0.461392,-0.190792,-1.210695,-2.210215,0.308951,-0.057145,1.859026,NaN,-0.269695,32.742834
6,0.784398,-0.382700,-0.635010,0.189111,-0.310170,0.240598,0.753878,0.216928,-0.108168,-0.586098,...,1.785643,0.804527,-0.026050,-1.364167,0.876982,-0.834078,1.624560,0.595359,1.356737,-813.606438
7,-1.919110,-0.502398,-0.443998,2.945112,-0.733891,-0.555276,0.257764,1.563856,-0.532898,-0.255989,...,0.181822,-0.728271,-1.682362,-0.332719,-0.137890,-0.114696,2.594162,NaN,-1.628567,362.979816
8,0.162938,2.051196,1.479045,-1.562278,1.799767,0.418559,0.606723,0.647076,-1.572640,-0.841949,...,0.422512,0.565458,-1.092555,-0.304089,-0.141261,-0.899892,1.313830,-0.399820,1.042088,-642.505580
9,0.651463,-0.735162,-1.560219,0.266378,-0.297301,0.346185,-0.932416,0.756884,0.751413,-1.060374,...,1.236996,-1.117987,1.069404,-0.050594,-0.061746,1.461063,0.854035,-0.660783,-1.164623,895.607057

In [4]:
# Display first 10 rows in Test dataset
display(Test.head(10))

,0,1,2,3,4,5,6,7,8,9,...,141,142,143,144,145,146,147,148,149,y
0,1.081816,-1.131037,0.108628,1.077395,-0.750072,-0.564374,0.505181,1.628797,0.454544,-1.373511,...,-0.438376,0.206104,-1.408897,1.976744,-1.117125,-1.897746,-0.522654,2.638855,-1.503102,NaN
1,1.435743,0.773806,0.250435,-0.451541,0.441791,0.137116,0.349729,0.095813,0.137996,0.468987,...,-0.581815,1.340089,1.217877,0.691981,0.115697,0.184174,-0.921121,0.221608,1.592319,NaN
2,0.415317,-0.581344,-0.245195,-0.315032,0.363002,-1.554639,-0.559687,-1.162702,2.325160,0.381909,...,-1.162827,0.763204,2.857790,0.142008,0.015687,-1.858612,0.447087,0.945012,-0.131331,NaN
3,0.178376,-0.329287,-0.924843,2.514518,-0.008991,0.678703,0.040802,0.286314,-2.073584,-0.748560,...,2.576744,0.432035,0.717691,2.406410,-0.483214,-0.638041,0.323221,-0.973862,-0.353541,NaN
4,1.217485,0.675895,2.390781,0.326706,0.342779,-1.964247,0.524710,-1.985868,0.423961,-0.660297,...,0.425173,-0.038636,0.537029,0.547327,0.503873,0.561255,1.404780,-0.104122,-0.924451,NaN
5,0.140106,0.382456,-0.127122,-1.119771,0.458747,-3.436277,-0.228845,-0.410870,0.025192,1.921239,...,0.060271,-0.683783,0.936039,-0.640786,1.178966,-0.626844,-1.016316,-1.108966,1.297157,NaN
6,0.149338,-1.929914,-1.120863,-0.043642,0.969424,-2.431424,-0.089162,0.652455,-0.211406,0.229038,...,0.032995,-0.552484,-0.604541,-0.436469,-1.328633,0.050813,1.440549,-0.178086,1.272635,NaN
7,0.728542,2.128252,-0.849019,-2.316782,-1.666356,1.194550,-0.315684,0.126875,-3.254223,1.058784,...,-0.583942,2.063978,-0.052602,0.186529,-1.357131,-0.604892,-0.550177,-1.208768,-0.558357,NaN
8,-1.931525,-0.001033,1.840331,-0.899644,0.195682,-0.991674,0.308840,-0.412611,0.716138,-0.578879,...,-0.394475,0.272912,-1.554583,-0.507571,1.295641,0.856341,-0.253962,0.647889,2.577960,NaN
9,-2.191199,-1.203643,-0.671067,-0.265129,-1.226484,-0.032887,0.012910,0.008804,0.466815,2.284283,...,0.478377,0.279806,0.890621,-0.466338,-0.907915,-1.111666,0.543902,0.018085,-0.668522,NaN

In [5]:
# display the General information of the Train dataset 
display(Train.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5880 entries, 0 to 5879
Columns: 151 entries, 0 to y
dtypes: float64(151)
memory usage: 6.8 MB

None

## exploratory data analysis

In [6]:
# Let's see how many Null values are present in the database
Train.isna().sum()

0        0
1        0
2        0
3        0
4        0
      ...
146      0
147      0
148    232
149      0
y        0
Length: 151, dtype: int64

In [7]:
# Now, we will drop all those rows which have + or - inf. values
Train = Train.replace([np.inf, -np.inf], np.nan).dropna(axis=0)

In [8]:
# Now let's check if there is any null value left
Train.isna().sum()

0      0
1      0
2      0
3      0
4      0
      ..
146    0
147    0
148    0
149    0
y      0
Length: 151, dtype: int64

In [9]:
# Display first 8 rows in Test dataset
Train.head(8)

,0,1,2,3,4,5,6,7,8,9,...,141,142,143,144,145,146,147,148,149,y
0,-0.746945,0.846646,-0.202470,0.028677,-0.229053,0.378089,-0.800458,0.414641,-1.504229,0.371135,...,-0.990873,0.864308,0.042010,-0.196266,-0.698771,-0.994566,-0.500914,0.003735,-0.353331,-456.665254
1,0.267893,0.686836,-2.099945,-0.356856,0.299254,0.098733,1.206721,-1.172500,-0.227677,2.061577,...,-0.540844,1.059226,-0.691391,0.029994,-0.566103,-0.885774,-1.312298,-0.938679,-1.134801,1058.205923
2,0.774361,0.812023,1.057683,-1.461385,-0.924284,0.323890,1.866386,0.326994,1.286274,-0.996723,...,0.247075,1.203377,0.765125,-0.427309,-0.563282,0.282035,0.126215,0.572231,-1.147129,-434.143673
3,-0.625636,-0.827090,0.602128,1.168934,0.814647,-0.800436,0.218008,0.355778,-0.448102,1.697075,...,0.717384,0.653825,1.290715,-0.439905,-0.202368,0.490357,-0.201219,-1.294190,-0.316879,977.514618
6,0.784398,-0.382700,-0.635010,0.189111,-0.310170,0.240598,0.753878,0.216928,-0.108168,-0.586098,...,1.785643,0.804527,-0.026050,-1.364167,0.876982,-0.834078,1.624560,0.595359,1.356737,-813.606438
8,0.162938,2.051196,1.479045,-1.562278,1.799767,0.418559,0.606723,0.647076,-1.572640,-0.841949,...,0.422512,0.565458,-1.092555,-0.304089,-0.141261,-0.899892,1.313830,-0.399820,1.042088,-642.505580
9,0.651463,-0.735162,-1.560219,0.266378,-0.297301,0.346185,-0.932416,0.756884,0.751413,-1.060374,...,1.236996,-1.117987,1.069404,-0.050594,-0.061746,1.461063,0.854035,-0.660783,-1.164623,895.607057
13,-1.046453,0.676589,-0.976662,0.915287,0.072303,0.029022,-0.060874,0.023030,-0.090538,0.523125,...,0.637846,0.144614,0.107622,-0.892374,-0.145821,0.907577,0.012186,-0.363756,0.846091,-97.776198

In [10]:
# display the General information of the Test dataset 
display(Test.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Columns: 151 entries, 0 to y
dtypes: float64(151)
memory usage: 141.7 KB

None

In [11]:
# Let's check if there is any null value in the Test Dataset
Test.isna().sum()

0        0
1        0
2        0
3        0
4        0
      ...
146      0
147      0
148      0
149      0
y      120
Length: 151, dtype: int64

## Split The Train DataSet into Training and Testing DataSet

In [12]:
# import the train_test_split function from the sklearn library
from sklearn.model_selection import train_test_split

In [13]:
# Apply the function and split the data 
x_train,x_test,y_train,y_test = train_test_split(Train.iloc[:,:150],
                                                 Train['y'],test_size = 0.25)

## DataSet Visual Representation!

In [14]:
# Display first 6 rows in x_train dataset
display(x_train.head(6))

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
1789,-0.070391,0.832355,1.840301,1.805849,0.432101,0.134447,-2.406208,0.043476,1.753557,-1.064008,...,-0.453865,0.234109,1.404011,0.673554,0.387905,-0.665169,0.317078,-0.144277,0.258399,0.714692
2038,0.813661,0.695048,0.746849,-1.726376,-0.259590,-0.226890,-0.623962,0.079961,0.607435,-0.898954,...,-0.662706,0.713614,-0.081410,-0.108768,-0.588131,0.169668,1.034355,0.955102,1.314072,-0.169232
1550,0.600399,1.276736,-0.021238,-0.920563,0.164216,0.245625,1.702769,1.380287,-1.902385,-1.686679,...,-0.928309,-1.638732,-0.240490,-0.481814,0.959729,0.837023,1.660434,-0.923255,-0.607726,0.060809
1699,-0.338716,-0.709137,0.789781,2.278781,0.004884,-0.800171,0.254939,-1.767886,0.401229,1.004782,...,-1.129929,0.710901,0.056624,-1.596012,-0.088190,0.140182,-0.479824,-0.762664,0.251534,1.829177
3494,-1.765988,-2.863302,-0.459805,0.874733,1.286842,-1.328609,-0.203865,-0.133923,1.735961,1.605310,...,-0.289466,-0.237831,-0.423439,-1.564199,-0.432494,-0.131880,-0.601958,0.041249,-0.137110,1.179710
3014,0.003536,-0.669554,1.162808,0.715298,1.647385,0.595505,0.391148,1.250025,-0.804204,0.913543,...,-1.233929,1.252229,0.568289,0.788169,0.229928,2.353914,-0.172270,-0.432180,-0.416169,-0.989598

In [15]:
# Display first 6 rows in x_train dataset
display(x_test.head(6))

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
5728,-0.016906,-0.595957,0.823612,-0.805969,-0.479264,-0.334164,-0.959640,-0.248851,-1.574789,1.604593,...,1.012209,0.764965,0.302734,0.748975,-0.282167,-0.414563,-1.139900,-0.071832,0.711792,0.002114
322,-0.824509,0.140845,-0.633736,1.308968,-0.601856,-0.184291,1.116971,0.768490,0.126471,0.241823,...,-0.673111,1.659409,0.994439,0.069093,1.383597,-0.051613,0.596662,-0.582293,-0.820395,2.215664
2602,-0.282068,-0.038637,0.387012,0.882928,0.571496,0.571116,-2.354195,0.393371,-0.624367,0.358474,...,-0.565880,0.074615,0.012997,0.572354,-0.028171,0.633496,1.698157,1.086442,2.068120,1.340462
1733,0.455483,1.561474,-0.734204,0.032940,0.152963,-0.993480,1.350441,0.014738,0.799489,0.279395,...,-1.471559,-0.447679,-0.283414,-0.404621,-0.281707,1.647821,-0.613722,0.243993,1.303252,-0.576409
1716,-0.352363,0.468270,0.734026,-0.427459,-0.340602,0.930961,-0.055054,0.625846,1.425643,0.374849,...,1.401218,0.155687,0.389708,1.683593,-0.189753,-0.686904,2.182935,0.600856,0.240203,-0.348609
922,-0.561421,-0.301504,-0.167353,1.356750,1.788683,-0.172913,-2.238609,0.550749,0.998185,1.706401,...,-0.243193,-0.805719,-0.477580,-0.898164,-0.258834,0.853159,0.738944,-0.289313,-0.934231,-0.978697

In [16]:
# Display first 6 rows in x_train dataset
display(y_train.head(6))

1789    171.329090
2038   -291.329605
1550    474.468703
1699   -262.649922
3494   -614.413515
3014     31.542453
Name: y, dtype: float64

## Create The Model and Fit it on The DataSet

In [17]:
# import the BayesianRidge Model from sklearn 
from sklearn.linear_model import BayesianRidge

# Define the Model
model = BayesianRidge()

# Fit The Model on the x_train, y_train Dataset 
model.fit(x_train,y_train)

# Get The Accuracy of The Model
model.score(x_test,y_test)

0.9686788980627984

## Now Predict The Class of Test DataSet Using The Model

In [18]:
# Predict on Test DataSet 
final_result = model.predict(Test.iloc[:,:150])

In [19]:
# Save the prediction as result.csv file in the local directory
final_result = pd.DataFrame(final_result)
final_result.to_csv('result.csv')